### ISSUE TITLE
Temperature - 800.00m?

### ISSUE THREAD

**Issue by Shizzlebix** [NightMan-1/netatmo-munin-go#2]
Hello,

i dont know how to fix, sry.

0,8 grad or something.... say munin 800.00m 
-0.2 are -200.00m

**Comment by NightMan-1** [comment]
Hello!

I do not know how to help with this :(

https://serverfault.com/questions/123761/what-does-the-m-unit-in-munin-mean
https://serverfault.com/questions/326281/how-to-read-the-scale-of-the-munin-monitoring-system-tomcat-accesses-by-day-gra
https://en.wikipedia.org/wiki/Milli-

**Comment by NightMan-1** [comment]
ok, i found way, update app :)

**Comment by Shizzlebix** [comment]
t@x
